Fix failure building the json

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -56,8 +56,9 @@ if [ -n "$FLUTTER_VERSION" ]; then
     cd flutter/
     git checkout $FLUTTER_VERSION
   fi
-  rm flutter.json
 
+  # Avoid failing if the file does not exist
+  rm flutter.json || true
 else
 
   print "Running flutter upgrade command"
